"""Boss Battle page for end-of-topic adventure challenges."""

from __future__ import annotations

import streamlit as st

from cpp_tutor.services.boss_battle_service import BossBattleService
from cpp_tutor.services.gamification_service import GamificationService
from cpp_tutor.services.practice_service import PracticeService
from cpp_tutor.services.progress_service import ProgressService
from cpp_tutor.utils.auth_guard import require_authentication

st.set_page_config(page_title="Boss Battle", page_icon="🐉", layout="wide")

user = require_authentication()
progress_service = ProgressService()
practice_service = PracticeService()
boss_battle_service = BossBattleService()
gamification_service = GamificationService()

try:
    rows = progress_service.get_topics_with_progress(user["id"])
except Exception as exc:  # noqa: BLE001
    st.error(f"Failed to load topics: {exc}. Please refresh the page.")
    st.stop()

boss_topics = [
    row
    for row in rows
    if practice_service.has_passed_practice(user["id"], row["id"])
    and boss_battle_service.has_boss_seed(row["id"])
]

st.title("Boss Battle")
st.caption("Boss Battle unlocks after you pass Practice for the same topic.")

if not boss_topics:
    st.warning("No boss battle is unlocked yet. Complete a practice challenge first.")
    st.page_link("pages/practice.py", label="Go to Practice", icon="💻")
    st.stop()

topic_title = st.selectbox("Select Topic", [row["title"] for row in boss_topics])
selected_topic = next(row for row in boss_topics if row["title"] == topic_title)
state_key = f"boss_{selected_topic['id']}"

if st.button("Generate Boss Battle", type="primary"):
    with st.spinner("Summoning the boss..."):
        try:
            battle = boss_battle_service.generate_boss_battle(selected_topic["id"], topic_title)
            st.session_state[state_key] = {
                "battle": battle,
                "provider": battle.provider_used,
            }
        except Exception as exc:  # noqa: BLE001
            st.error(f"Failed to generate boss battle: {exc}")

battle_state = st.session_state.get(state_key)
battle = battle_state["battle"] if battle_state else boss_battle_service.get_latest_boss_battle(selected_topic["id"])

if battle:
    st.subheader(battle.title)
    st.caption(f"Difficulty: {battle.difficulty}")
    if battle.provider_used:
        st.caption(f"Generated by: {battle.provider_used}")

    answers: list[str] = []
    for idx, question in enumerate(battle.questions, start=1):
        st.markdown(f"### MCQ {idx}. {question.question}")
        answer = st.radio(
            label=f"Boss answer for Q{idx}",
            options=question.options,
            key=f"{state_key}_q_{idx}",
            label_visibility="collapsed",
        )
        answers.append(answer)

    st.markdown("### Final Coding Challenge")
    st.write(battle.coding_title)
    st.markdown(battle.coding_description)
    st.write(f"Expected Concepts: {battle.coding_expected_concepts}")
    submitted_code = st.text_area(
        "Your Boss Battle Solution",
        value=battle.coding_starter_code,
        height=320,
        key=f"{state_key}_code",
    )

    if st.button("Submit Boss Battle"):
        if not submitted_code.strip():
            st.error("Please enter your coding solution before submitting.")
        else:
            with st.spinner("Evaluating boss battle..."):
                try:
                    result = boss_battle_service.evaluate_boss_battle(
                        topic_title=topic_title,
                        boss_battle=battle,
                        answers=answers,
                        submitted_code=submitted_code,
                    )
                    boss_battle_service.save_attempt(
                        student_id=user["id"],
                        topic_id=selected_topic["id"],
                        boss_battle_id=battle.id or 0,
                        result=result,
                        provider_used=battle_state["provider"] if battle_state else battle.provider_used or "unknown",
                    )

                    st.write(f"MCQ Score: {result.mcq_score}%")
                    st.write(f"Coding Score: {result.coding_score}%")
                    st.write(f"Overall Score: {result.overall_score}%")
                    if result.passed:
                        st.success("Boss defeated. New world progression unlocked.")
                        awarded = progress_service.award_xp_once(
                            student_id=user["id"],
                            topic_id=selected_topic["id"],
                            action="BOSS_BATTLE_WIN",
                            xp_amount=200,
                        )
                        gamification_service.register_boss_battle_completion(user["id"])
                        if awarded:
                            st.info("Rewards: +200 XP and Boss Conqueror badge")
                        else:
                            st.info("Boss Battle reward already awarded for this topic")
                    else:
                        st.warning("Boss battle not cleared yet. Train more and retry.")

                    st.markdown(result.coding_feedback)
                    if result.strengths:
                        st.write("Strengths:")
                        for item in result.strengths:
                            st.write(f"- {item}")
                    if result.improvements:
                        st.write("Improvements:")
                        for item in result.improvements:
                            st.write(f"- {item}")

                    with st.expander("Review MCQ explanations"):
                        for idx, question in enumerate(battle.questions, start=1):
                            st.write(f"Q{idx} answer: {question.answer}")
                            st.write(question.explanation)
                except Exception as exc:  # noqa: BLE001
                    st.error(f"Failed to evaluate boss battle: {exc}")
else:
    st.info("Generate a boss battle to start the challenge.")