"""Practice page for coding exercise generation, submission, evaluation, and rewards."""

from __future__ import annotations

import streamlit as st

from cpp_tutor.services.gamification_service import GamificationService
from cpp_tutor.services.practice_service import PracticeService
from cpp_tutor.services.progress_service import ProgressService
from cpp_tutor.utils.auth_guard import require_authentication

st.set_page_config(page_title="Practice", page_icon="💻", layout="wide")

user = require_authentication()
progress_service = ProgressService()
practice_service = PracticeService()
gamification_service = GamificationService()

try:
    rows = progress_service.get_topics_with_progress(user["id"])
except Exception as exc:  # noqa: BLE001
    st.error(f"Failed to load topics: {exc}. Please refresh the page.")
    st.stop()

practice_topics = [row for row in rows if row["status"] == "COMPLETED" and row["score"] >= 80]

st.title("Coding Practice")
st.caption("Practice unlocks only after you pass the quiz for the same topic.")

if not practice_topics:
    st.warning("No practice topic is unlocked yet. Pass a topic quiz first.")
    st.page_link("pages/quiz.py", label="Go to Quiz", icon="🧠")
    st.stop()

topic_title = st.selectbox("Select Topic", [row["title"] for row in practice_topics])
selected_topic = next(row for row in practice_topics if row["title"] == topic_title)
state_key = f"practice_{selected_topic['id']}"

if st.button("Generate Coding Exercise", type="primary"):
    with st.spinner("Generating coding exercise..."):
        try:
            exercise = practice_service.generate_exercise(selected_topic["id"], topic_title)
            st.session_state[state_key] = {
                "exercise": exercise,
                "provider": exercise.provider_used,
            }
        except Exception as exc:  # noqa: BLE001
            st.error(f"Failed to generate coding exercise: {exc}")

practice_state = st.session_state.get(state_key)
exercise = None
if practice_state:
    exercise = practice_state["exercise"]
else:
    exercise = practice_service.get_latest_exercise(selected_topic["id"])

if exercise:
    st.subheader(exercise.title)
    if exercise.provider_used:
        st.caption(f"Generated by: {exercise.provider_used}")
    st.markdown(exercise.description)
    st.write(f"Expected Concepts: {exercise.expected_concepts}")
    st.code(exercise.starter_code, language="cpp")

    submitted_code = st.text_area(
        "Your C/C++ Solution",
        value=exercise.starter_code,
        height=300,
        key=f"{state_key}_code",
    )

    if st.button("Submit Practice Solution"):
        if not submitted_code.strip():
            st.error("Please enter your solution before submitting.")
        else:
            with st.spinner("Evaluating submission..."):
                try:
                    result = practice_service.evaluate_submission(
                        topic_title=topic_title,
                        exercise=exercise,
                        submitted_code=submitted_code,
                    )
                    practice_service.save_submission(
                        student_id=user["id"],
                        topic_id=selected_topic["id"],
                        exercise_id=exercise.id or 0,
                        submitted_code=submitted_code,
                        result=result,
                        provider_used=practice_state["provider"] if practice_state else exercise.provider_used or "unknown",
                    )

                    st.write(f"Score: {result.score}%")
                    if result.passed:
                        st.success("Practice completed successfully.")
                        awarded = progress_service.award_xp_once(
                            student_id=user["id"],
                            topic_id=selected_topic["id"],
                            action="PRACTICE_COMPLETE",
                            xp_amount=100,
                        )
                        gamification_service.register_coding_exercise_completion(user["id"])
                        if awarded:
                            st.info("Reward: +100 XP")
                        else:
                            st.info("Practice XP already awarded for this topic")
                        st.page_link("pages/boss_battle.py", label="Enter Boss Battle", icon="🐉")
                    else:
                        st.warning("Practice not passed yet. Review feedback and try again.")

                    st.markdown(result.feedback)
                    if result.strengths:
                        st.write("Strengths:")
                        for item in result.strengths:
                            st.write(f"- {item}")
                    if result.improvements:
                        st.write("Improvements:")
                        for item in result.improvements:
                            st.write(f"- {item}")
                except Exception as exc:  # noqa: BLE001
                    st.error(f"Failed to evaluate practice submission: {exc}")
else:
    st.info("Generate a coding exercise to start practice.")