"""Quiz page for generation, submission, scoring, and XP awarding."""

from __future__ import annotations

import streamlit as st

from cpp_tutor.services.progress_service import ProgressService
from cpp_tutor.services.quiz_service import QuizService
from cpp_tutor.utils.auth_guard import require_authentication

st.set_page_config(page_title="Quiz", page_icon="🧠", layout="wide")

user = require_authentication()
progress_service = ProgressService()
quiz_service = QuizService()

try:
    rows = progress_service.get_topics_with_progress(user["id"])
except Exception as exc:  # noqa: BLE001
    st.error(f"Failed to load topics: {exc}. Please refresh the page.")
    st.stop()

quiz_topics = [row for row in rows if row["status"] in {"UNLOCKED", "COMPLETED"}]

st.title("Quiz Generator")
if not quiz_topics:
    st.warning("No topic is unlocked yet.")
    st.stop()

topic_title = st.selectbox("Select Topic", [row["title"] for row in quiz_topics])
selected_topic = next(row for row in quiz_topics if row["title"] == topic_title)
state_key = f"quiz_{selected_topic['id']}"

theory_completed = progress_service.has_read_theory(user["id"], selected_topic["id"])
if not theory_completed:
    st.warning("You must complete the theory step for this topic before taking the quiz.")
    st.page_link("pages/theory.py", label="Go to Theory", icon="📘")
    st.stop()

if st.button("Generate 5-Question Quiz", type="primary"):
    with st.spinner("Generating quiz..."):
        try:
            questions, response = quiz_service.generate_quiz(topic_title)
            st.session_state[state_key] = {
                "questions": questions,
                "provider": response.provider_used,
            }
        except Exception as exc:  # noqa: BLE001
            st.error(f"Quiz generation failed: {exc}")

quiz_state = st.session_state.get(state_key)
if quiz_state:
    st.caption(f"Generated by: {quiz_state['provider']}")
    questions = quiz_state["questions"]

    answers: list[str] = []
    for idx, question in enumerate(questions, start=1):
        st.markdown(f"### Q{idx}. {question.question}")
        answer = st.radio(
            label=f"Choose answer for Q{idx}",
            options=question.options,
            key=f"{state_key}_q_{idx}",
            label_visibility="collapsed",
        )
        answers.append(answer)

    if st.button("Submit Quiz"):
        result = quiz_service.evaluate(questions, answers)
        progress_service.mark_quiz_result(user["id"], selected_topic["id"], result.score)

        if result.passed:
            st.success(f"PASS - Score: {result.score}% ({result.correct}/{result.total})")
            pass_awarded = progress_service.award_xp_once(
                student_id=user["id"],
                topic_id=selected_topic["id"],
                action="QUIZ_PASS",
                xp_amount=20,
            )
            perfect_awarded = False
            if result.score == 100:
                perfect_awarded = progress_service.award_xp_once(
                    student_id=user["id"],
                    topic_id=selected_topic["id"],
                    action="QUIZ_PERFECT",
                    xp_amount=50,
                )

            reward_text = []
            if pass_awarded:
                reward_text.append("+20 XP")
            if perfect_awarded:
                reward_text.append("+50 XP (Perfect)")
            if reward_text:
                st.info("Rewards: " + ", ".join(reward_text))
            st.page_link("pages/practice.py", label="Continue to Practice", icon="💻")
        else:
            st.warning(f"RETRY - Score: {result.score}% ({result.correct}/{result.total})")

        with st.expander("Review explanations"):
            for idx, question in enumerate(questions, start=1):
                st.write(f"Q{idx} answer: {question.answer}")
                st.write(question.explanation)
