"""Theory learning page powered by LLM router."""

from __future__ import annotations

import streamlit as st

from cpp_tutor.services.progress_service import ProgressService
from cpp_tutor.services.theory_service import TheoryService
from cpp_tutor.utils.auth_guard import require_authentication

st.set_page_config(page_title="Theory", page_icon="📘", layout="wide")

user = require_authentication()
progress_service = ProgressService()
theory_service = TheoryService()

try:
    rows = progress_service.get_topics_with_progress(user["id"])
except Exception as exc:  # noqa: BLE001
    st.error(f"Failed to load topics: {exc}. Please refresh the page.")
    st.stop()

available_topics = [row for row in rows if row["status"] in {"UNLOCKED", "COMPLETED"}]

st.title("Theory Module")
if not available_topics:
    st.warning("No topic is unlocked yet. Complete previous quizzes to unlock more.")
    st.stop()

topic_title = st.selectbox(
    "Select Topic",
    options=[row["title"] for row in available_topics],
)
selected_topic = next(row for row in available_topics if row["title"] == topic_title)

if st.button("Generate Theory", type="primary"):
    with st.spinner("Generating lesson..."):
        try:
            response = theory_service.generate_theory(topic_title)
            st.session_state["latest_theory"] = {
                "topic_id": selected_topic["id"],
                "topic": topic_title,
                "content": response.text,
                "provider": response.provider_used,
            }
        except Exception as exc:  # noqa: BLE001
            st.error(f"Failed to generate theory: {exc}")

latest = st.session_state.get("latest_theory")
if latest and latest.get("topic") == topic_title:
    st.caption(f"Generated by: {latest['provider']}")
    st.markdown(latest["content"])

    if st.button("Mark Theory as Read (+10 XP)"):
        awarded = progress_service.award_xp_once(
            student_id=user["id"],
            topic_id=selected_topic["id"],
            action="THEORY_READ",
            xp_amount=10,
        )
        if awarded:
            st.success("+10 XP awarded")
        else:
            st.info("Theory XP already awarded for this topic")
